Registration page
VSRudnyk/wallet_frontend pull request #11
Opened 2022-07-29 16:24 UTC by MashtalerOlha

2022-07-29 17:05 UTC, VSRudnyk commented on src/pages/RegistrationPage.styled.jsx
> +    background-image: url(../images/EllipseGray.png), url(../images/EllipsePink.png);
Нужно сделать импорт изображений
import ellipseGray from '../image/EllipseGray.png'

2022-07-29 17:05 UTC, VSRudnyk requested changes
Сделай импорт изображений

2022-07-29 20:03 UTC, VSRudnyk requested changes
Импорт изображений

2022-07-30 10:46 UTC, MashtalerOlha commented on src/pages/RegistrationPage.styled.jsx
> +    background-image: url(../images/EllipseGray.png), url(../images/EllipsePink.png);
перевіряй

2022-07-30 11:59 UTC, VSRudnyk approved these changes

2022-07-30 11:59 UTC, merged